version: '3.8'

networks:
  txt-me-network:
    name: txt-me-network

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    networks:
      - txt-me-network
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"

  # DynamoDB admin console at http://localhost:8001
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    networks:
      - txt-me-network
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000